---
title: "homework4"
author: "Amanda Walz"
date: "October 27, 2018"
output: pdf_document
---

```{r setup_global_options, eval = TRUE, include=FALSE}


library(readr)
library(dplyr)
library(tidyr)
library(broom)
library(sf)
library(tigris)
library(purrr)
library(ggplot2)
library(knitr)
library(scales)
```
#Homicide arrest rates in different major cities across the United States.#

```{r homicide_data}
homicide_url <- paste0("https://raw.githubusercontent.com/washingtonpost/data-homicides/master/homicide-data.csv")

#Load in data and tidy data
homi_data <- read_csv(homicide_url)
homi_table <- homi_data %>% 
  unite(col = city_name, city, state, sep = ", ")

#Creating table with counts by city
pre_unsolved <- homi_table %>% 
  select(city_name, disposition) %>%
  mutate(not_solved = disposition %in% c("Closed without arrest", "Open/No arrest")) %>% 
  filter(not_solved == TRUE) %>% 
  group_by(city_name) %>% 
  count() %>% 
  rename(total_unsolved = n) %>% 
  ungroup()

pre_unsolved2 <- homi_table %>% 
  select(city_name) %>% 
  group_by(city_name) %>% 
  count() %>% 
  rename(total_homicide = n) %>% 
  ungroup() 

unsolved <- left_join(pre_unsolved, pre_unsolved2, by = "city_name")
```

```{r prop_test}
#Run prop test on baltimore data 
baltimore_summary <- unsolved %>% 
  slice(3) 
baltimore_prob <- prop.test(
  x = baltimore_summary$total_unsolved,
  n = baltimore_summary$total_homicide)
baltimore_prob
tidy(baltimore_prob)
```

```{r final_plot_tidy}
#Tidying data for final graph
unsolved_prop <- map2(unsolved$total_unsolved, unsolved$total_homicide, prop.test) %>% 
  map_df(tidy) %>% 
  select(estimate, conf.low, conf.high) %>% 
  mutate(city_name = unsolved$city_name)
kable(unsolved_prop,
      caption = "Unsolved Homicides by City")
```

```{r final_plot, fig.height=11}
plot_data <- full_join(unsolved, unsolved_prop) %>%
  select(-total_homicide, -total_unsolved) %>% 
  arrange(desc(estimate))

homicide_plot <- plot_data %>%
  mutate(city_name = reorder(city_name, estimate)) %>% 
  ggplot(mapping = aes(x = estimate, y = city_name)) +
  geom_point(color = "White") +
  geom_errorbarh(aes(xmin = plot_data$conf.low,
                 xmax = plot_data$conf.high),
                 height = 0,
                 color = "white") +
  scale_x_continuous(name = "Percent of homicides that are unsolved", labels = percent) +
  theme_dark() +
  ggtitle("Unsolved homicides by city", 
          "Bars show 95% confidence inverval") +
  ylab(NULL)
homicide_plot
```